### ISSUE TITLE
addlistas.php fitxategian insert intoarekin arazoa

### ISSUE THREAD

**Issue by Davidzubi93** [Davidzubi93/php-todo-app#1]
Kaixo @zmwebdev,

lista berri bat gehitu nahi dudanean, honako errore hau ematen dit

**Fatal error**: Call to a member function prepare() on a non-object in **/home/ubuntu/workspace/addlistas.php** on line **11**

**Comment by zmwebdev** [comment]
``` php
$listas= $add->prepare("INSERT INTO listas (ID, nombre) VALUES ($listaId, $lista_nombre)");
```

$add aldagaia ez dago ondo, $dbh da.
